# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            Fortran FOSS Programmers
tagline:          'A community homepage for F/OSS Fortran programmers on Github'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://Fortran-FOSS-Programmers.github.io

author:
  name:           'Izaak Beekman'
  url:            https://twitter.com/zbeekman

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/Fortran-FOSS-Programmers/Fortran-FOSS-Programmers.github.io

gems:             [jekyll-paginate]
